/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.JsonParseException;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class App {

    @Override
    public String toString() {
        return "";
    }

    public static void main(String[] args)  {
         Gson gson = new Gson();
         Quote[] q;
         try(BufferedReader bufferedReader = new BufferedReader(new FileReader("C:\\Users\\USER\\newforGradle\\quotes\\app\\src\\main\\resources\\recentquotes.json"))) {
            q= gson.fromJson(bufferedReader, Quote[].class);
            if(q.length >0 && q!=null){
                int random = (int)Math.floor(Math.random() * (q.length - 0 + 1) + 0);
                System.out.println(q[random]);
            }

         } catch (IOException | JsonParseException e) {
             e.printStackTrace();
             throw new RuntimeException(e);
         }


    }
}
