/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

import static com.google.gson.GsonBuilder.*;
import static quotes.QouteWrapper.getQuotesFromApi;
import static quotes.QouteWrapper.saveQuotesToJson;

public class App {

    @Override
    public String toString() {
        return "";
    }

    public static void main(String[] args) throws IOException {


        Gson gson = new Gson();
        Quote[] q;
        try(BufferedReader bufferedReader2 = new BufferedReader(new FileReader("app/src/main/resources/recentquotes.json"))) {
            q= gson.fromJson(bufferedReader2, Quote[].class);
            if(q.length >0 && q!=null){
                int random = (int)Math.floor(Math.random() * (q.length - 0 + 1) + 0);
                System.out.println(q[random]);
            }

        } catch (IOException | JsonParseException e) {
            e.printStackTrace();
            throw new RuntimeException(e);
        }


        System.out.println(" ");
        System.out.println("Lab 9");
        System.out.println(" ");

//        QouteWrapper qw =new QouteWrapper();
//        System.out.println(qw.getQuotesFromApi());
//        qw.saveQuotesToJson(qw.getQuotesFromApi().getQuote(),"app/src/main/resources/quoteFromApi.json");


        List<Quote> quoteList = new ArrayList<>();
        QouteWrapper newQuoteWrapper = getQuotesFromApi();
        for (int i = 0; i < 10; i++) {

            Quote newQuote = newQuoteWrapper.getQuote();
            quoteList.add(newQuote);
        }


        if(quoteList.size() >0 && quoteList!=null) {
            int random = (int) Math.floor(Math.random() * (quoteList.size() + 1) + 0);

            System.out.println(newQuoteWrapper.getQuotesFromApi());
        }


        saveQuotesToJson(quoteList, "app/src/main/resources/quoteFromApi.json");




    }
}